name: calliope_NL
channels:
    - conda-forge
    - gurobi
dependencies:
    - python=3.12
    - jupyterlab
    - gurobi=11.0
    - pip
    - pip:
        - git+https://github.com/calliope-project/calliope/.git@67fce7593e9e3485c4235d4815bf62115ce2aff9
